#!/bin/bash

# SNMPv3 setup for Debian
# Installs and configures snmpd (SNMPv3 only) on UDP/161
# Creates a read-only SNMPv3 user with the strongest supported auth/priv methods
# Restricts UDP/161 by source CIDR via nftables firewall rules
# Writes a summary to ~/snmpd.creds (for the invoking user)
# Run the script -> bash -c "$(curl -fsSL https://raw.githubusercontent.com/celalettinb-art/snmp/refs/heads/main/change-snmpv3-settings-on-debian.sh)"

CONFIG_FILE="/etc/snmp/snmpd.conf"
CONFIG_DIR="$(dirname "$CONFIG_FILE")"
DATE="$(date +%Y%m%d)"
BACKUP_FILE="$CONFIG_DIR/snmpd.conf_${DATE}.bak"
CREDS_FILE="$HOME/snmpd.creds"

# Colors
YELLOW_BOLD="\e[1;33m"
GREEN="\e[32m"
RED="\e[31m"
CYAN="\e[36m"
RESET="\e[0m"

# Root check
if [[ $EUID -ne 0 ]]; then
  echo -e "${RED}ERROR: This script must be run as root.${RESET}"
  exit 1
fi

# Backup existing configuration
if [[ -f "$CONFIG_FILE" ]]; then
  cp "$CONFIG_FILE" "$BACKUP_FILE"
  echo -e "${GREEN}INFO: Backup created at $BACKUP_FILE${RESET}"
else
  echo -e "${RED}ERROR: SNMP configuration file not found.${RESET}"
  exit 1
fi

# User input
read -rp "$(echo -e "${YELLOW_BOLD}Enter the allowed IP address range (e.g. 192.168.1.0/24): ${RESET}")" ALLOWED_IP

# sysLocation (mandatory)
while true; do
  read -rp "$(echo -e "${YELLOW_BOLD}Enter sysLocation: ${RESET}")" SYSLOCATION
  [[ -n "$SYSLOCATION" ]] && break
done

# sysContact (mandatory + email validation)
EMAIL_REGEX="^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$"
while true; do
  read -rp "$(echo -e "${YELLOW_BOLD}Enter sysContact (valid email address): ${RESET}")" SYSCONTACT
  [[ "$SYSCONTACT" =~ $EMAIL_REGEX ]] && break
  echo -e "${RED}ERROR: Invalid email address.${RESET}"
done

# SNMPv3 credentials
while true; do
  read -rp "$(echo -e "${YELLOW_BOLD}Enter SNMPv3 username: ${RESET}")" SNMP_USER
  [[ -n "$SNMP_USER" ]] && break
done

while true; do
  read -rsp "$(echo -e "${YELLOW_BOLD}Enter SNMPv3 password (min. 8 chars): ${RESET}")" SNMP_PASS
  echo
  [[ ${#SNMP_PASS} -ge 8 ]] && break
  echo -e "${RED}ERROR: Password must be at least 8 characters long.${RESET}"
done

# Write new configuration
cat > "$CONFIG_FILE" <<EOF
###############################################################################
# SNMPv3 configuration generated by script
# Allowed IP range: $ALLOWED_IP
# NOTE: Access restriction is enforced by the firewall
###############################################################################

agentAddress udp:161

sysLocation $SYSLOCATION
sysContact $SYSCONTACT

# Disable SNMP v1/v2c
disableAuthorization yes

# SNMPv3 User
createUser $SNMP_USER SHA "$SNMP_PASS" AES "$SNMP_PASS"
rouser $SNMP_USER authPriv
EOF

# Save credentials
cat > "$CREDS_FILE" <<EOF
SNMPv3 Configuration Credentials
--------------------------------
Username    : $SNMP_USER
Auth Level  : authPriv
Auth Algo   : SHA
Crypto Algo : AES
Allowed IP  : $ALLOWED_IP
Config File : $CONFIG_FILE
EOF

chmod 600 "$CREDS_FILE"

# Restart SNMP service
systemctl restart snmpd

# Summary
echo -e "\n${CYAN}================ Configuration Summary ================${RESET}"
echo -e "${GREEN}SNMP Version     : SNMPv3 only${RESET}"
echo -e "${GREEN}Username         : $SNMP_USER${RESET}"
echo -e "${GREEN}Auth Level       : authPriv${RESET}"
echo -e "${GREEN}Auth Algorithm   : SHA${RESET}"
echo -e "${GREEN}Crypto Algorithm : AES${RESET}"
echo -e "${GREEN}Allowed IP Range : $ALLOWED_IP${RESET}"
echo -e "${GREEN}sysLocation      : $SYSLOCATION${RESET}"
echo -e "${GREEN}sysContact       : $SYSCONTACT${RESET}"
echo -e "${CYAN}-------------------------------------------------------${RESET}"
echo -e "${CYAN}Config file      : $CONFIG_FILE${RESET}"
echo -e "${CYAN}Credentials file : $CREDS_FILE${RESET}"
echo -e "${CYAN}Backup file      : $BACKUP_FILE${RESET}"
