#!/usr/bin/env bash

# Description: Install and configure SNMPv3 on Debian with secure defaults.
# All messages are in English, interactive questions are bold and yellow.
# This script configures snmpd for SNMPv3 only, on UDP port 161.
# It stores credentials and settings also in ~/snmpd.creds.

set -euo pipefail

SNMPD_CONF="/etc/snmp/snmpd.conf"
CREDS_FILE="$HOME/snmpd.creds"

# Colors
BOLD_YELLOW="\e[1;33m"
BOLD_GREEN="\e[1;32m"
BOLD_RED="\e[1;31m"
BOLD_CYAN="\e[1;36m"
RESET="\e[0m"

# Checks
if [[ $EUID -ne 0 ]]; then
  echo -e "${BOLD_RED}Error: This script must be run as root (use sudo).${RESET}"
  exit 1
fi

command -v apt >/dev/null 2>&1 || {
  echo -e "${BOLD_RED}Error: This script is intended for Debian/Ubuntu systems with apt.${RESET}"
  exit 1
}

# Helper to ask non-empty input
ask_non_empty() {
  local prompt="$1"
  local var
  while true; do
    echo -en "${BOLD_YELLOW}${prompt}${RESET} "
    read -r var
    if [[ -n "${var}" ]]; then
      printf '%s\n' "${var}"
      return 0
    else
      echo -e "${BOLD_RED}Input must not be empty. Please try again.${RESET}"
    fi
  done
}

# Helper: validate email (simple regex)
validate_email() {
  local email="$1"
  [[ "$email" =~ ^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$ ]]
}

ask_email() {
  local prompt="$1"
  local email
  while true; do
    echo -en "${BOLD_YELLOW}${prompt}${RESET} "
    read -r email
    if [[ -z "$email" ]]; then
      echo -e "${BOLD_RED}E-mail address must not be empty.${RESET}"
      continue
    fi
    if validate_email "$email"; then
      printf '%s\n' "$email"
      return 0
    else
      echo -e "${BOLD_RED}Invalid e-mail address format. Please try again.${RESET}"
    fi
  done
}

# Helper: ask IP/CIDR range (basic sanity)
validate_cidr() {
  local cidr="$1"
  # Very simple IP/CIDR check; you may tighten if needed.
  [[ "$cidr" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}(/[0-9]{1,2})?$ ]]
}

ask_cidr() {
  local prompt="$1"
  local cidr
  while true; do
    echo -en "${BOLD_YELLOW}${prompt}${RESET} "
    read -r cidr
    if [[ -z "$cidr" ]]; then
      echo -e "${BOLD_RED}IP range must not be empty.${RESET}"
      continue
    fi
    if validate_cidr "$cidr"; then
      printf '%s\n' "$cidr"
      return 0
    else
      echo -e "${BOLD_RED}Invalid IPv4 or CIDR format. Example: 192.168.1.0/24 or 192.168.1.10${RESET}"
    fi
  done
}

# Helper: random credentials
generate_random_string() {
  local length="$1"
  # Requires openssl
  if ! command -v openssl >/dev/null 2>&1; then
    echo -e "${BOLD_RED}Error: openssl is required but not installed.${RESET}"
    exit 1
  fi
  openssl rand -base64 48 | tr -dc 'A-Za-z0-9' | head -c "$length"
}

# Install SNMP packages if needed
echo -e "${BOLD_CYAN}Checking SNMP packages...${RESET}"
if ! dpkg -s snmpd >/dev/null 2>&1 || ! dpkg -s snmp >/dev/null 2>&1; then
  echo -e "${BOLD_CYAN}Installing snmpd and snmp packages...${RESET}"
  apt update
  apt install -y snmpd snmp
else
  echo -e "${BOLD_GREEN}snmpd and snmp are already installed.${RESET}"
fi

# Ask for configuration values
SYSLOCATION="$(ask_non_empty 'Enter SNMP sysLocation (e.g. "Server Room RZ-1"):')"
SYSCONTACT="$(ask_email 'Enter SNMP sysContact (valid e-mail address):')"
ALLOWED_RANGE="$(ask_cidr 'Enter allowed IP range for SNMP queries (e.g. 192.168.1.0/24):')"

# Generate SNMPv3 user and passwords
echo -e "${BOLD_CYAN}Generating SNMPv3 credentials...${RESET}"
SNMPV3_USER="snmpv3_$(generate_random_string 8)"
SNMPV3_AUTH_PASS="$(generate_random_string 20)"
SNMPV3_PRIV_PASS="$(generate_random_string 32)"

# Info: authPriv with SHA and AES-256 is considered state of the art if supported
# We use SHA auth and AES-256 privacy (encryption).
AUTH_PROTO="SHA"
PRIV_PROTO="AES"

# Backup existing config
if [[ -f "$SNMPD_CONF" ]]; then
  BACKUP="${SNMPD_CONF}.$(date +%Y%m%d%H%M%S).bak"
  echo -e "${BOLD_CYAN}Backing up existing snmpd.conf to ${BACKUP}${RESET}"
  cp "$SNMPD_CONF" "$BACKUP"
fi

echo -e "${BOLD_CYAN}Writing secure SNMPv3-only configuration...${RESET}"

cat > "$SNMPD_CONF" <<EOF
###############################################################################
# SNMP daemon configuration - generated by setup script
# Only SNMPv3 is enabled; SNMPv1/v2c are disabled.
#
# NOTE: IP access restriction for SNMP queries is expected to be enforced
#       at the firewall level as well. Allowed range (firewall): ${ALLOWED_RANGE}
###############################################################################

# Run as Debian-snmp user
agentuser  Debian-snmp
agentgroup Debian-snmp

# Listen on UDP port 161 on all IPv4 interfaces by default.
# You may restrict to a specific interface/IP if desired.
agentAddress udp:161

###############################################################################
# System information
###############################################################################
sysLocation    ${SYSLOCATION}
sysContact     ${SYSCONTACT}

###############################################################################
# SNMPv3 user configuration
# "authPriv" enforces authentication and encryption.
# Authentication: ${AUTH_PROTO}
# Privacy (encryption): ${PRIV_PROTO}
###############################################################################

# Create SNMPv3 user
createUser ${SNMPV3_USER} ${AUTH_PROTO} "${SNMPV3_AUTH_PASS}" ${PRIV_PROTO} "${SNMPV3_PRIV_PASS}"
rouser     ${SNMPV3_USER} authPriv

###############################################################################
# Access control
###############################################################################

# By default, restrict view to the entire OID tree
view   all    included   .1                               80

###############################################################################
# Legacy SNMP versions disabled
###############################################################################
# No community strings, no v1/v2c access defined here.

EOF

# Make sure correct permissions
chown root:snmp "$SNMPD_CONF" 2>/dev/null || true
chmod 640 "$SNMPD_CONF" 2>/dev/null || true

# Enable and restart snmpd
echo -e "${BOLD_CYAN}Enabling and restarting snmpd service...${RESET}"
systemctl enable snmpd
systemctl restart snmpd

# Write credentials file in user's home
echo -e "${BOLD_CYAN}Writing credentials to ${CREDS_FILE}...${RESET}"
cat > "$CREDS_FILE" <<EOF
SNMP configuration summary
==========================

Config file: ${SNMPD_CONF}

sysLocation: ${SYSLOCATION}
sysContact:  ${SYSCONTACT}

Allowed IP range (firewall level): ${ALLOWED_RANGE}

SNMPv3 user:           ${SNMPV3_USER}
SNMPv3 auth protocol:  ${AUTH_PROTO}
SNMPv3 auth password:  ${SNMPV3_AUTH_PASS}
SNMPv3 privacy proto:  ${PRIV_PROTO}
SNMPv3 privacy passwd: ${SNMPV3_PRIV_PASS}

Example snmpwalk command:
snmpwalk -v3 -l authPriv -u "${SNMPV3_USER}" -a ${AUTH_PROTO} -A "${SNMPV3_AUTH_PASS}" -x ${PRIV_PROTO} -X "${SNMPV3_PRIV_PASS}" localhost
EOF

chmod 600 "$CREDS_FILE"

# Final colored summary
echo
echo -e "${BOLD_GREEN}SNMPv3 setup completed successfully.${RESET}"
echo
echo -e "${BOLD_YELLOW}Relevant information:${RESET}"
echo -e "${BOLD_CYAN}  SNMP config file: ${SNMPD_CONF}${RESET}"
echo -e "${BOLD_CYAN}  sysLocation:      ${SYSLOCATION}${RESET}"
echo -e "${BOLD_CYAN}  sysContact:       ${SYSCONTACT}${RESET}"
echo -e "${BOLD_CYAN}  Allowed range (firewall): ${ALLOWED_RANGE}${RESET}"
echo -e "${BOLD_CYAN}  SNMPv3 user:      ${SNMPV3_USER}${RESET}"
echo -e "${BOLD_CYAN}  Auth protocol:    ${AUTH_PROTO}${RESET}"
echo -e "${BOLD_CYAN}  Priv protocol:    ${PRIV_PROTO}${RESET}"
echo
echo -e "${BOLD_YELLOW}Credentials and summary have been written to:${RESET} ${BOLD_GREEN}${CREDS_FILE}${RESET}"
echo
echo -e "${BOLD_YELLOW}Reminder:${RESET} Ensure your firewall allows UDP/161 from ${ALLOWED_RANGE}."
